### ISSUE TITLE
[REST API] Get product image from REST API

### ISSUE THREAD

**Issue by 12evgen** [TemplateInvaders/ti-woocommerce-wishlist#18]
Currently, there is a request to REST Api, which returns a list of products that were added to the wishlist.
But the in response is not enough product info, such as:
1) product image
2) product name
![image](https://user-images.githubusercontent.com/25562185/71250167-2d6e2780-2349-11ea-88a2-ed529931c32b.png)

Will this data be added in the future?

**Comment by doozy** [comment]
Hi @12evgen 

This API request returns only data that saved in the custom plugin database table. We don't want to add additional code to get the default WooCommerce product object because it will add more database queries.

To help achieve your idea we added filter `tinvwl_api_wishlist_get_products_response` that could be hooked for response modifications. You can add a small function that will add requested data to the default response in case you don't want to make an extra calls to WooCommerce REST API for product object.
