### ISSUE TITLE
Printing

### ISSUE THREAD

**Issue by dhuibh** [TemplateInvaders/ti-woocommerce-wishlist#30]
With a woeful lack of support from Template Invaders (four emails, no response) I turn to the community to ask... Why is there no ability to print a saved wishlist? and YES, this IS an issue. A LARGE issue. This shortcoming really needs to be resolved.

**Comment by doozy** [comment]
Hi @dhuibh 

The printing feature including in any browser. How your LARGE issue could be related to our plugin?

The plugin adding extra features to your shop while an active theme responsible for a design including a print layout also. 

It's definitely not a plugin feature to handle a print design.

**Comment by dhuibh** [comment]
Yeah, NO. It’s not up to the browser to organize and print a list - it’s up to the plugin. Nobody prints browser renders with page headers and footers for your list output, that’s amateur bullshit. 
 And NO. It’s not up to the theme to create a page layout and hook into YOUR plugin which may or may not get installed.
And YES. It IS the job of your plugin to PRINT. 
That you push it aside and say “not my job” is weak and corrupt. If you don’t know how to code it you shouldn’t be selling it.

Give me my money back and fix your broken software.

Regards,
M

**Comment by dhuibh** [comment]
You need support? NOTHING.
You want your money back? NOTHING.
What is wrong with this guy?!

**Comment by doozy** [comment]
Hey @dhuibh ,

You didn't get my previous message properly. It wasn't like the simple “not my job”. I tried to explain to you how it should work. In simple words, printing depends on the page stylesheets. It's a "monkey job" to override all styles from the plugin. So usually it's doing the fine-tuning stage for the whole website setup. You can't activate plugins and a theme and get a perfectly desired website. You always need to do some final customization to fit everything to your needs.

It's why we can't and don't want to include such a feature in a public plugin.

On another note, we have a feature on our to-do list to export a wishlist in PDF format. But this is a different story and the design of the export file could be 100% controlled by the plugin.

It looks like you are the type of person who trying to get extra features for free threatening us with bad reviews, refunds, etc. Sorry, we don't play this game.

If you want and eligible to get 14 days money back you will definitely get it, don't worry. 

Our support started replies to all of the requests that we got during last month when we didn't provide support in a regular way. Be patient, you will get a reply from them asap. Sorry for the inconvenience.

I'll close this topic because we will not implement this feature in our plugin.

Kind regards.

**Comment by dhuibh** [comment]
There was no mistaking what you wrote. You didn’t try to “explain” anything. You flipped off not just me but everyone who uses your plugin! Now you try to backtrack and claim to have the ability to print a wishlist to PDF from some plugin NOT on your website. I would have bought that had I known about it and had you not just have been an arrogant little b*tch.

Experience tells us that people react based on who they really are. You reacted as if I wanted something for nothing, a thief - meaning that is obviously who YOU are.

I wanted what I paid for… support for a legit question asked within the first HOUR of paying USD$199 for… wait for it… SUPPORT! It took 18 DAYS to get blown off by you and be treated like sh*t on your shoe. I didn’t ask for “extra features” and I didn’t threaten “bad reviews”. I DID ask for my money back immediately after you finally posted one of the dumbest, most ignorant answers ever. 

But this post tops that one! You backtrack, point fingers, claim a solution (which nobody can see), insult me again, say I must be “eligible” for a 14 day refund (after waiting longer than that to answer) and admit you have not provided support… to ANYONE. 

Wow. Even you have to admit, you suck at this. 

And it’s too bad because it’s not an awful plugin. It mostly does what it is supposed to do. 
But I want my money back because there is ZERO support and YOU are just a f*cking a**hole.

Kind Regards.

**Comment by doozy** [comment]
@dhuibh 

I'm really sorry for you that you live in such a cruel world.

**Comment by dhuibh** [comment]
Ahahaha! Having your head that far up your ass must be causing your lack of oxygen. Dumbf*ck.
