### ISSUE TITLE
Escaping characters in the settings page buttons

### ISSUE THREAD

**Issue by TedTodd** [TemplateInvaders/ti-woocommerce-wishlist#8]
The buttons on the settings page are being rendered incorrectly, for example the quick save button is outputting:
`<button type="submit" name="save_buttons-setting_save_quick" value="<span><i class=" fa="" fa-floppy-o"="">Save" id="tinvwl_save_buttons-setting_save_quick" class="form-control" &gt;<span><i class="fa fa-floppy-o"></i></span>Save</button>`

The " characters in the font awesome are causing issues in the value of the button.

I've implented a fix on my end to swap around the lines in admin/settings/general.class.php to these:
`'std'  => "<span><i class='fa fa-floppy-o'></i></span>" . __( "Save", "ti-woocommerce-wishlist" ),`

Not sure if just an issue for me, but I've had it happen over multiple installs and can't find a conflicting plugin.

**Comment by StanMarsh** [comment]
Hi,

It looks like the issue is local and something breaks the output in your case. The string to fix the issue you've provided, persists in **admin/settings/general.class.php** file from the first plugin release and it has never been changed:

`'std'  => '<span><i class="fa fa-floppy-o"></i></span>' . __( 'Save', 'ti-woocommerce-wishlist' ),`
